export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'

export const SET_ERRORS='SET_ERRORS'
export const REMOVE_ERRORS='REMOVE_ERRORS'

export const USER_LOADED='USER_LOADED'
export const AUTH_FAIL='AUTH_FAIL'

export const GET_USER='GET_USER'
export const GET_ALL_USERS='GET_ALL_USERS'

export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'

export const LOGOUT='LOGOUT'

export const GET_PROFILE='GET_PROFILE'
export const PROFILE_ERROR='PROFILE_ERROR'


export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const CREATE_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const POST_LOADING= 'POST_LOADING';

export const RESET_USER='RESET_USER'
export const RESET_POST='RESET_POST'
export const RESET_PROFILE='RESET_PROFILE'

export const UPDATE_LIKES='UPDATE_LIKES'

export const UPDATE_FOLLOW_ERS_ING='UPDATE_FOLLOW_ERS_ING'


export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const GET_COMMENTS = 'GET_COMMENTS';

